apiVersion: v1
kind: Pod
metadata:
  namespace: mudit
  labels:
    run: pod1
  name: pod1
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - 'sleep $ok'
    image: alpine
    name: pod1
    env:
     - name: ok
       valueFrom:
        configMapKeyRef:
         name: mydata1
         key: x
