---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: nikhilpod
spec:
 replicas: 2
 template:
  metadata:
   labels:
    app: hellonginx
  spec:
   containers:
    - name: nginx-pod
      image: nikhilsid26/nginx:nk
      ports:
       - containerPort: 80
      imagePullPolicy: IfNotPresent       
