apiVersion: v1
kind: Service
metadata:
 name: nikdep1service    #this will create single IP to access pods

spec:
 type: ClusterIP   # only can access from cluster means either master or worker
 ports:
  - targetPort: 80 # port of pod -- in reality port of container - this field is optional
    port: 80   # this field is mandatory and this is port of service IP
 selector:
  name: nikapp
          
